class Solution {
    public List<List<Integer>> threeSum(int[] nums) {
        Arrays.sort(nums); // TC---> O(nlogn)
         List<List<Integer>> ans=new ArrayList<>();
        for (int i = 0; i < nums.length-2; i++) {
            // to avoid duoplicates enries we do the follwoing
            if (i != 0 && nums[i] == nums[i - 1]) {
                continue;
            }
            // if i had to sort---> i will use two pointers trather than using HashMaps
            int j = i + 1;
            int k = nums.length - 1;
            while (j < k) {
                long val = (long)nums[i] + nums[j] + nums[k];// to avoid integer overflow
                if(val==0){
                   ans.add(Arrays.asList(nums[i],nums[j],nums[k]));
                    j++;
                    k--;
                    // we need to skip the duplicates that are generated by j and k
                    while(j<nums.length &&nums[j]==nums[j-1]){
                        j++;
                    }
                    while(k>=0 && nums[k]==nums[k+1]){
                        k--;
                    }
                    continue;
                }
                if(val>0){
                    k--;
                }
                else{
                    j++;
                }
            }
        }

        return ans;
    }
}
